/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['example.js']) {
  _$jscoverage['example.js'] = [];
  _$jscoverage['example.js'][1] = 0;
  _$jscoverage['example.js'][2] = 0;
  _$jscoverage['example.js'][3] = 0;
}
_$jscoverage['example.js'][1]++;
(function () {
  _$jscoverage['example.js'][2]++;
  this.hooray = (function () {
  _$jscoverage['example.js'][3]++;
  return "hooray!";
});
})(this);
_$jscoverage['example.js'].source = ["(function(){","\tthis.hooray = function(){","\t\treturn \"hooray!\";","\t};","})(this);"];
